const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const AxeBuilder=require('@axe-core/playwright').default;
const fs=require('node:fs');
const output=process.env.GIFTY_SCREENSHOTS||'/tmp/gifty-browser';
fs.mkdirSync(output,{recursive:true});
const base=process.env.GIFTY_TEST_URL||'http://127.0.0.1:8088';
const audit=async p=>{await p.waitForTimeout(250);const result=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[])};
(async()=>{
const browser=await chromium.launch({...(process.env.GIFTY_CHROME?{executablePath:process.env.GIFTY_CHROME}:{}),headless:true});
const email='alex'+Date.now()+'@example.com';
const errors=[];const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.getByRole('heading',{name:'Organise a gift exchange'}).waitFor();await audit(page);await page.screenshot({path:output+'/home-desktop.png',fullPage:true});
await page.locator('header').getByRole('link',{name:'Create an account'}).click();await page.getByLabel('Your name').fill('Alex Morgan');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('a sufficiently long password');await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByRole('heading',{name:'Exchanges',exact:true}).waitFor();await page.getByRole('link',{name:'New exchange',exact:true}).first().click();await page.getByRole('button',{name:'Create exchange',exact:true}).click();await page.getByText('Enter a name for the exchange.').waitFor();assert.equal(await page.evaluate(()=>document.activeElement.id),'name','focus not on the empty field');await page.getByLabel('Exchange name').fill('The December get-together');await page.getByLabel('Exchange date').fill('2099-12-20');await page.getByLabel('Note for everyone').fill('Bring your gift wrapped. We’ll meet at Alex’s for dinner.');await page.getByRole('button',{name:'Create exchange',exact:true}).click();await page.getByRole('heading',{name:'The December get-together'}).waitFor();const exchangeURL=page.url();const invitation=await page.getByLabel('Invitation link').inputValue();await audit(page);await page.screenshot({path:output+'/exchange-desktop.png',fullPage:true});
const guests=[];
for(const name of ['Bea','Charlie']){const ctx=await browser.newContext();const p=await ctx.newPage();await p.goto(invitation);await p.getByText(/^Alex Morgan has invited you/).waitFor();await p.getByRole('link',{name:'Create an account to join'}).click();await p.getByLabel('Your name').fill(name);await p.getByLabel('Email address').fill(name+Date.now()+'@example.com');await p.getByLabel('Password',{exact:true}).fill('another long password here');await p.getByRole('button',{name:'Create an account',exact:true}).click();await p.getByRole('heading',{name:'The December get-together'}).waitFor();await p.getByRole('link',{name:'Wish list',exact:true}).click();await p.getByRole('button',{name:'Add idea'}).click();await p.getByLabel('What is it?').fill(name+'’s favourite book');await p.getByLabel('Link (optional)').fill('https://example.com/book');await p.getByLabel('Details').fill('A paperback would be lovely.');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('heading',{name:name+'’s favourite book'}).waitFor();guests.push({p,ctx});}
await page.reload();await page.getByRole('button',{name:'Draw names',exact:true}).click();const dlg=page.getByRole('dialog');assert.deepEqual(await dlg.locator('.draw-list li').allTextContents(),['Alex Morgan','Bea','Charlie']);assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Cancel','dialog focus not on Cancel');await dlg.getByRole('button',{name:'Draw names for 3 people',exact:true}).click();await page.locator('#to-name').waitFor();assert(await page.evaluate(()=>!!document.activeElement.closest('.to')),'recipient not focused on first view');assert.equal(await page.getByRole('heading',{name:/^You’re buying for /}).count(),1);assert.equal(await page.locator('#toast').textContent(),'','toast competes with the reveal');assert(await page.getByRole('heading',{name:/favourite book/}).count());await audit(page);await page.screenshot({path:output+'/drawn-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await audit(page);await page.screenshot({path:output+'/drawn-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile horizontal overflow');
await page.getByRole('link',{name:'Wish list',exact:true}).click();await page.getByRole('button',{name:'Add idea'}).click();await audit(page);await page.getByLabel('What is it?').fill('A handmade mug');await page.getByLabel('Details').fill('Dark green, if possible.');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'A handmade mug'}).waitFor();await page.getByRole('button',{name:'Edit A handmade mug',exact:true}).click();await page.getByLabel('What is it?').fill('A green handmade mug');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'A green handmade mug'}).waitFor();await audit(page);await page.screenshot({path:output+'/wishes-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Remove A green handmade mug'}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove A green handmade mug',exact:true}).click();await page.getByRole('heading',{name:'No ideas yet'}).waitFor();
for(const {p} of guests){await p.goto(exchangeURL);await p.locator('.to.arrive #to-name').waitFor();await p.reload();await p.locator('.to:not(.arrive) #to-name').waitFor();assert.equal(await p.getByRole('button',{name:'Draw names',exact:true}).count(),0)}
await page.getByRole('link',{name:'Account',exact:true}).click();await page.getByRole('button',{name:'Sign out'}).click();await page.getByRole('heading',{name:'Organise a gift exchange'}).waitFor();await page.setViewportSize({width:375,height:812});await audit(page);await page.screenshot({path:output+'/home-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'home overflow');await page.locator('header').getByRole('link',{name:'Sign in',exact:true}).click();await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('a sufficiently long password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Exchanges',exact:true}).waitFor();await page.setViewportSize({width:320,height:740});await audit(page);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px overflow');assert.deepEqual(errors,[]);console.log('PASS: signup, invitations, three participants, private draw, wish create/edit/remove, logout/sign-in, desktop/mobile, accessibility, no JS errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
