// Email flows against a server started with GIFTY_SMTP_HOST=log, reading emails from its log.
// GIFTY_TEST_URL=http://127.0.0.1:8089 GIFTY_MAIL_LOG=server.log node tests/email.cjs
const {chromium}=require('playwright');const AxeBuilder=require('@axe-core/playwright').default;const fs=require('fs');const assert=require('assert/strict');
const base=process.env.GIFTY_TEST_URL||'http://127.0.0.1:8089',out=process.env.GIFTY_SCREENSHOTS||'/tmp/gifty-browser',logf=process.env.GIFTY_MAIL_LOG;if(!logf)throw Error('Set GIFTY_MAIL_LOG to the server log file.');fs.mkdirSync(out,{recursive:true});
const mails=()=>fs.readFileSync(logf,'utf8').replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/g,(_,h)=>String.fromCharCode(parseInt(h,16)));
const tok=(to,route)=>{const all=mails().split('email to ').filter(m=>m.startsWith(to));const m=[...all.at(-1).matchAll(new RegExp('#'+route+'/([A-Za-z0-9_-]+)','g'))];assert(m.length,'no '+route+' link for '+to);return m.at(-1)[1]};
const audit=async p=>{await p.waitForTimeout(200);const r=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>v.id+' '+v.nodes.map(n=>n.target).join()),[])};
(async()=>{const b=await chromium.launch({...(process.env.GIFTY_CHROME?{executablePath:process.env.GIFTY_CHROME}:{}),headless:true});const errors=[];
const ctx=await b.newContext({viewport:{width:390,height:844}});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));const s=Date.now();const ana='ana'+s+'@example.com';
await p.goto(base+'/#signup');await p.getByLabel('Your name').fill('Ana Lima');await p.getByLabel('Email address').fill(ana);await p.getByLabel('Password',{exact:true}).fill('first long password');await p.getByRole('button',{name:'Create an account'}).click();
await p.getByText('Confirm your email address to get emails').waitFor();await audit(p);await p.waitForTimeout(4600);await p.screenshot({path:out+'/mail-notice.png'});
await p.getByRole('link',{name:'Account',exact:true}).click();await p.getByRole('button',{name:'Send the link again'}).waitFor();await audit(p);await p.screenshot({path:out+'/mail-account-unverified.png',fullPage:true});
await p.waitForTimeout(500);await new Promise(r=>setTimeout(r,1500));
await p.goto(base+'/#verify/'+tok(ana,'verify'));await p.getByRole('heading',{name:'Email address confirmed'}).waitFor();await audit(p);
await p.getByRole('link',{name:'Go to exchanges'}).click();await p.getByRole('heading',{name:'Exchanges',exact:true}).waitFor();assert.equal(await p.getByText('Confirm your email address to get emails').count(),0);
await p.getByRole('link',{name:'Account',exact:true}).click();const box=p.getByRole('checkbox');await box.waitFor();assert(await box.isChecked());await box.uncheck();await p.getByText('Exchange emails turned off.').waitFor();await box.check();await p.getByText('Exchange emails turned on.').waitFor();await p.screenshot({path:out+'/mail-account.png',fullPage:true});
// Two more people and a draw, through the API.
const others=[];for(const n of ['Ben','Cat']){const c=await b.newContext();const q=await c.newPage();await q.goto(base);await q.evaluate(async([n,s])=>{await fetch('/api/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n,email:n+s+'@example.com',password:'another long password'})})},[n,s]);others.push(q)}
const e=await p.evaluate(async()=>{const r=await fetch('/api/exchanges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Office swap',date:'2099-12-18',budget:'20',currency:'GBP',note:''})});return r.json()});
for(const q of others)await q.evaluate(async code=>{await fetch('/api/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})})},e.invite);
await p.evaluate(async id=>{await fetch('/api/exchanges/'+id+'/draw',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})},e.id);
await new Promise(r=>setTimeout(r,2000));
const draw=mails().split('email to ').filter(m=>m.startsWith(ana)).at(-1);fs.writeFileSync(out+'/draw-email.txt',draw);assert(draw.includes('Draw a name'));assert(!/Ben|Cat/.test(draw.split('\n--\n')[0].replace('Office swap','')),'draw email names a recipient');
const api=(path,body)=>p.evaluate(async([path,body])=>(await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})).json(),[path,body]);
await p.goto(base+'/#exchange/'+e.id);const def=p.getByRole('form',{name:'Default reminders for everyone'}),mine=p.getByRole('form',{name:'Your reminders for this exchange'});await p.getByText('Change reminders').click();await def.waitFor();
await def.getByRole('button',{name:'Add a reminder'}).click();const row=def.locator('.rem-row').last();await row.getByLabel('How many').fill('3');await row.getByLabel('Days, weeks or months').selectOption('day');await def.getByRole('button',{name:'Save for everyone'}).click();await p.getByText('Reminders saved.').waitFor();
let st=await api('exchanges/'+e.id);assert.deepEqual(st.reminders.map(r=>r.n+r.unit),['1week','3day','1day']);assert.equal(st.mine.source,'organiser');
await p.getByText('Change reminders').click();await def.getByRole('button',{name:'Cancel'}).click();assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Change reminders','focus not back on Change after Cancel');assert(!(await def.isVisible()),'editor still open after Cancel');
await p.getByText('Change reminders').click();await p.getByText('Use different reminders for me').click();await mine.getByRole('button',{name:'Remove this reminder'}).first().click();assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('aria-label')),'How many','focus not moved after removing');await mine.getByRole('button',{name:'Save my reminders'}).click();await p.getByText('Reminders saved.').last().waitFor();await p.getByText('Change reminders').click();await mine.waitFor();assert.equal(await mine.locator('select').last().evaluate(s=>s.selectedOptions[0].textContent),'day');
await p.getByRole('button',{name:'Go back to my default'}).click();await p.getByText('Using the organiser’s choice.',{exact:true}).waitFor();
await p.getByRole('button',{name:'Draw a name'}).click();await p.waitForTimeout(2200);await p.getByRole('checkbox',{name:'I’ve got their gift ready'}).check();await p.getByText('None. Your gift is ready.').waitFor();await p.getByText('1 of 3 are ready').waitFor();await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>document.activeElement.name),'ready','focus lost after saving');await audit(p);assert.equal(await p.evaluate(()=>document.activeElement.name),'ready','focus moved by the scan');assert(await p.evaluate(()=>document.querySelector('.skip').getBoundingClientRect().bottom<=0),'skip link on screen');await p.screenshot({path:out+'/reminders-mobile.png',fullPage:true});
await p.reload();await p.getByText('None. Your gift is ready.').waitFor();assert(await p.getByRole('checkbox',{name:'I’ve got their gift ready'}).isChecked(),'done not saved');st=await api('exchanges/'+e.id);assert.equal(st.mine.source,'organiser');
await p.setViewportSize({width:1440,height:1000});await p.waitForTimeout(4700);await p.screenshot({path:out+'/reminders-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});
await p.goto(base+'/#account');const acct=p.getByRole('group',{name:'Reminders',exact:true});await acct.waitFor();await acct.getByLabel('Use my own in every exchange').check();await p.getByText('Using your own reminders. Change them below.').waitFor();
const af=p.getByRole('form',{name:'Your reminders for every exchange'});const first=af.locator('.rem-row').first();await first.getByLabel('Days, weeks or months').selectOption('month');await first.getByLabel('How many').fill('2');await af.getByRole('button',{name:'Save reminders'}).click();await p.getByText('Reminders saved.').waitFor();
await p.waitForTimeout(300);assert(await p.evaluate(()=>document.activeElement.textContent.startsWith('Add a reminder')),'focus lost on account page');await audit(p);await p.screenshot({path:out+'/account-reminders.png',fullPage:true});
const me=await api('me');assert.deepEqual([me.ownReminders,me.reminders.map(r=>r.n+r.unit)],[true,['2month','1day']]);assert.equal((await api('exchanges/'+e.id)).mine.source,'account');
await acct.getByLabel('Use each organiser’s choice').check();await p.getByText('Using each organiser’s choice.').waitFor();
// Wish scope: Ben adds a work-only idea in a second exchange; it must not show up for whoever draws him in Office swap.
const ben=others[0];const second=await api('exchanges',{name:'Family',date:'2099-12-24',budget:'10',currency:'GBP',note:''});await ben.evaluate(async code=>{await fetch('/api/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})})},second.invite);
await ben.goto(base+'/#wishes/'+second.id);await ben.reload();await ben.getByRole('button',{name:'Add idea'}).click();await ben.getByLabel('What is it?').fill('Family-only jigsaw');assert(await ben.getByLabel('Only in these exchanges').isChecked(),'scope did not default to the exchange');await audit(ben);await ben.screenshot({path:out+'/wish-scope-dialog.png'});await ben.getByRole('button',{name:'Save',exact:true}).click();
await ben.getByRole('heading',{name:'Only in Family'}).waitFor();await ben.getByRole('heading',{name:'Family-only jigsaw'}).waitFor();await audit(ben);await ben.screenshot({path:out+'/wishes-grouped.png',fullPage:true});
for(const q of [p,...others]){const x=await q.evaluate(async id=>(await fetch('/api/exchanges/'+id)).json(),e.id);if(x.recipient&&/^Ben/.test(x.recipient.name))assert(!x.recipient.wishes.some(w=>w.title==='Family-only jigsaw'),'family-only idea leaked into Office swap')}
await p.goto(base+'/#unsubscribe/'+tok(ana,'unsubscribe'));await p.getByRole('button',{name:'Stop emails'}).click();await p.getByText('Done. You can turn exchange emails back on').waitFor();await audit(p);await p.screenshot({path:out+'/mail-unsub.png'});
await p.goto(base+'/#account');await p.reload();await p.getByRole('checkbox').waitFor();assert(!(await p.getByRole('checkbox').isChecked()));
await p.getByRole('link',{name:'Account',exact:true}).click();await p.getByRole('button',{name:'Sign out'}).click();await p.getByRole('heading',{name:'Organise a gift exchange'}).waitFor();await p.getByRole('link',{name:'Create an account'}).first().waitFor();await p.goto(base+'/#login');await p.getByRole('link',{name:'Forgotten your password?'}).click();await p.getByRole('heading',{name:'Reset your password'}).waitFor();await p.getByLabel('Email address').fill(ana);await p.getByRole('button',{name:'Send reset link'}).click();await p.getByRole('heading',{name:'Check your email'}).waitFor();await audit(p);await p.screenshot({path:out+'/mail-forgot.png'});
await p.goto(base+'/#reset/'+tok(ana,'reset'));await p.getByLabel('New password',{exact:true}).fill('second long password');await audit(p);await p.screenshot({path:out+'/mail-reset.png'});await p.getByRole('button',{name:'Save password'}).click();await p.getByRole('heading',{name:'Exchanges',exact:true}).waitFor();
await p.setViewportSize({width:320,height:700});await audit(p);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320 overflow');await p.screenshot({path:out+'/mail-320.png'});
assert.deepEqual(errors,[]);console.log('PASS email flows');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
